apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraft-controller
  namespace: confluent-operator

spec:
  replicas: 3

  image:
    application: quay.io/tonyfieit75/kafka-kraft:s390x-3.6.1
    init: quay.io/tonyfieit75/confluent-init-container:v0.1351.35-s390x

  storage:
    type: persistent
    class: managed-nfs-storage
    size: 20Gi

  dataVolumeCapacity: 20Gi

  podTemplate:
    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 1000780000

    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

    initContainerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

  configOverrides:

    #
    # REQUIRED (controller-only config)
    #
    server:
      - process.roles=controller
      - node.id=0
      - broker.id=0
      - controller.listener.names=CONTROLLER
      - listeners=CONTROLLER://:9093
      - listener.security.protocol.map=CONTROLLER:PLAINTEXT
      - controller.quorum.voters=0@kraft-controller-0:9093,1@kraft-controller-1:9093,2@kraft-controller-2:9093
      - log.dirs=/var/lib/kafka/data
      - metric.reporters=

    #
    # REQUIRED BY CFK EVEN IF BROKER IS NOT USED
    #
    broker:
      - metric.reporters=

